server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tang-dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/ ,file:${my-file-data}
  jackson:
    date-format: yyyy.MM.dd



#开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:dao/*.xml

#日志
#logging.file.path = D:\\log
#logging.level.web = ERROR

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

tang:
  security:
    rememberMe: true
    openUrl: /password,/doLogin,/verify,/verifyMail/*,/,/post/*,/author/*,/login,/so,/blog/comment/*,/register,/blog/blogs,/map,/**.*,/**/*.*,/blog/like,/blog/home/*,/blog/so
    privateUrl: /**/insert,/**/delete,/**/update,/fans/*

# 上传文件保存路径
# 外部静态文件位置
my-file-data: D://file
# 文件存储位置 file / 文件对象
my-file-data-path: ${my-file-data}/${my-file-static-path}
# 访问路径
my-file-static-path: obj

