SELECT BS1.BLOG_SUBJECT_ID ,BS1.SUBJECT_NAME ,BS1.CREATE_DATE,A1.AUTHOR_ID ,A1.USERNAME ,A1.NICKNAME  ,BS1.SYNOPSIS ,B1.BLOG_ID ,B1.TITLE ,B1.SYNOPSIS ,B1.CREATE_DATE
FROM DTS_BLOG_SUBJECT BS1
INNER JOIN UTS_AUTHOR A1 ON A1.AUTHOR_ID  = BS1.AUTHOR_ID AND A1.USERNAME = 'leilei'
LEFT JOIN DTS_BLOG_SUBJECT_RELATION BSR1 ON BSR1.BLOG_SUBJECT_ID = BS1.BLOG_SUBJECT_ID
LEFT JOIN DTS_BLOG B1 ON B1.BLOG_ID  = BSR1.BLOG_ID