package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticleSubjectRelation;
import net.ttcxy.tang.portal.entity.model.DtsArticleSubjectRelationExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleSubjectRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    long countByExample(DtsArticleSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int deleteByExample(DtsArticleSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int deleteByPrimaryKey(String articleSubjectRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int insert(DtsArticleSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int insertSelective(DtsArticleSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    DtsArticleSubjectRelation selectByPrimaryKey(String articleSubjectRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsArticleSubjectRelation record, @Param("example") DtsArticleSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int updateByExample(@Param("record") DtsArticleSubjectRelation record, @Param("example") DtsArticleSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int updateByPrimaryKeySelective(DtsArticleSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject_relation
     *
     * @mbg.generated Sun Dec 26 21:34:36 CST 2021
     */
    int updateByPrimaryKey(DtsArticleSubjectRelation record);
}