package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticleSubject;
import net.ttcxy.tang.portal.entity.model.DtsArticleSubjectExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(DtsArticleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(DtsArticleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String articleSubjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(DtsArticleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(DtsArticleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    DtsArticleSubject selectByPrimaryKey(String articleSubjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") DtsArticleSubject record, @Param("example") DtsArticleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") DtsArticleSubject record, @Param("example") DtsArticleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(DtsArticleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_subject
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKey(DtsArticleSubject record);
}