package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticleContent;
import net.ttcxy.tang.portal.entity.model.DtsArticleContentExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(DtsArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(DtsArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(DtsArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(DtsArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    DtsArticleContent selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") DtsArticleContent record, @Param("example") DtsArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") DtsArticleContent record, @Param("example") DtsArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") DtsArticleContent record, @Param("example") DtsArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(DtsArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(DtsArticleContent record);
}