package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticle;
import net.ttcxy.tang.portal.entity.model.DtsArticleExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(DtsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(DtsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(DtsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(DtsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    DtsArticle selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") DtsArticle record, @Param("example") DtsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") DtsArticle record, @Param("example") DtsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") DtsArticle record, @Param("example") DtsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(DtsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(DtsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKey(DtsArticle record);
}