package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticleLike;
import net.ttcxy.tang.portal.entity.model.DtsArticleLikeExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    long countByExample(DtsArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByExample(DtsArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByPrimaryKey(String likeArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insert(DtsArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insertSelective(DtsArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    DtsArticleLike selectByPrimaryKey(String likeArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsArticleLike record, @Param("example") DtsArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExample(@Param("record") DtsArticleLike record, @Param("example") DtsArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKeySelective(DtsArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_like
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKey(DtsArticleLike record);
}