package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsArticleTag;
import net.ttcxy.tang.portal.entity.model.DtsArticleTagExample;
import org.apache.ibatis.annotations.Param;

public interface DtsArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    long countByExample(DtsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByExample(DtsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByPrimaryKey(String articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insert(DtsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insertSelective(DtsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    DtsArticleTag selectByPrimaryKey(String articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsArticleTag record, @Param("example") DtsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExample(@Param("record") DtsArticleTag record, @Param("example") DtsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKeySelective(DtsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKey(DtsArticleTag record);
}