package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.DtsNotice;
import net.ttcxy.tang.portal.entity.model.DtsNoticeExample;
import org.apache.ibatis.annotations.Param;

public interface DtsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(DtsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(DtsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(DtsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(DtsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    DtsNotice selectByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") DtsNotice record, @Param("example") DtsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") DtsNotice record, @Param("example") DtsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(DtsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKey(DtsNotice record);
}