package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.PersistentLogins;
import net.ttcxy.tang.portal.entity.model.PersistentLoginsExample;
import org.apache.ibatis.annotations.Param;

public interface PersistentLoginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    long countByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    PersistentLogins selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExample(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKey(PersistentLogins record);
}