package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.StsConfig;
import net.ttcxy.tang.portal.entity.model.StsConfigExample;
import org.apache.ibatis.annotations.Param;

public interface StsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    long countByExample(StsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByExample(StsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByPrimaryKey(String configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insert(StsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insertSelective(StsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    StsConfig selectByPrimaryKey(String configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") StsConfig record, @Param("example") StsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExample(@Param("record") StsConfig record, @Param("example") StsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKeySelective(StsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sts_config
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKey(StsConfig record);
}