package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.UtsAuthor;
import net.ttcxy.tang.portal.entity.model.UtsAuthorExample;
import org.apache.ibatis.annotations.Param;

public interface UtsAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(UtsAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(UtsAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(UtsAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(UtsAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    UtsAuthor selectByPrimaryKey(String authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") UtsAuthor record, @Param("example") UtsAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") UtsAuthor record, @Param("example") UtsAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(UtsAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKey(UtsAuthor record);
}