package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.UtsResource;
import net.ttcxy.tang.portal.entity.model.UtsResourceExample;
import org.apache.ibatis.annotations.Param;

public interface UtsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    long countByExample(UtsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByExample(UtsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insert(UtsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int insertSelective(UtsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    UtsResource selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") UtsResource record, @Param("example") UtsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByExample(@Param("record") UtsResource record, @Param("example") UtsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKeySelective(UtsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_resource
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    int updateByPrimaryKey(UtsResource record);
}