package net.ttcxy.tang.portal.mapper;

import net.ttcxy.tang.portal.entity.model.UtsRole;
import net.ttcxy.tang.portal.entity.model.UtsRoleExample;
import org.apache.ibatis.annotations.Param;

public interface UtsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    long countByExample(UtsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByExample(UtsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insert(UtsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int insertSelective(UtsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    UtsRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") UtsRole record, @Param("example") UtsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByExample(@Param("record") UtsRole record, @Param("example") UtsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKeySelective(UtsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_role
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    int updateByPrimaryKey(UtsRole record);
}