server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/tang
    username: as
    password: as
    data: data.sql
  sql:
    init:
      mode: never #always never
  jpa:
    database: h2
    hibernate:
      ddl-auto: 'update'
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-admin-password: as
  main:
    allow-circular-references: true
  jackson:
    default-property-inclusion: non-null
    date-format: yyyy.MM.dd
    time-zone: GMT+8
    locale: zh_CN
  mvc:
    throwExceptionIfNoHandlerFound: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml,mapper/dao/**.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

tang:
  openUrl: /api/ws/**,/api/register,/,/*.html,/src/main/resources/favicon.ico,/**/*.html,/**/*.css,/**/*.js,/h2-console/**,/swagger-ui/**,/swagger-resources/**,/swagger-resources,/v3/api-docs,/**/*.jpg,/**/*.*,/api/authenticate,/error,/api/refresh
  tokenKey: Token
  jwt:
    base64-secret: 6IKv5a6a5pivSkZL5ouJ6JCo6YWx6LGG6IWQ6ICD6JmRYXNr5bCx5Zyw5pa56Imw6Ium5ouJ6JCo5aSn5a625Y+RYWtzZGZqbGthc2RqZmtsYXNkamZsa+WPkeWjq+Wkp+Wkq+WViuaJi+WKqOmYgOaJi+WKqOmYgOmYv+aWr+iSguiKrOmYv+aWr+iSguiKrA==
    token-validity-in-seconds: 108000
    token-validity-in-seconds-for-remember-me: 1000000000000

tang-file: D://obj
tang-http: false