insert into uts_author (author_id,mail,nickname,password,refresh_time,signature,update_time,create_time,username) values ('1','admin@admin.com','admin','$2a$10$mZbVEMls/YLv3cvFkGMoQOpgENyrmUtMnXagfl6qVjHOzOqLrtMbO',now(),'System Admin User',now(),now(),'admin');
insert into uts_author_role (author_role_id,author_id,create_time,role_id) values ('1','1',now(),'1');
insert into uts_resource (resource_id,create_time,name,path,state,type) values ('1',now(),'all','/**',9,'get');
insert into uts_resource (resource_id,create_time,name,path,state,type) values ('2',now(),'all','/**',9,'post');
insert into uts_resource (resource_id,create_time,name,path,state,type) values ('3',now(),'all','/**',9,'put');       
insert into uts_resource (resource_id,create_time,name,path,state,type) values ('4',now(),'all','/**',9,'delete');
insert into uts_resource_role (resource_role_id,create_time,resource_id,role_id) values ('1',now(),'1','1');
insert into uts_resource_role (resource_role_id,create_time,resource_id,role_id) values ('2',now(),'2','1');
insert into uts_resource_role (resource_role_id,create_time,resource_id,role_id) values ('3',now(),'3','1');
insert into uts_resource_role (resource_role_id,create_time,resource_id,role_id) values ('4',now(),'4','1');
insert into uts_role (role_id,role_name,role_value,create_time,refresh_time,update_time) values ('1','admin','role_admin',now(),now(),now());