package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsArticleTagRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_tag_relation.article_tag_relation_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    private String articleTagRelationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_tag_relation.article_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_tag_relation.article_tag_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    private String articleTagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_tag_relation.create_date
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_article_tag_relation
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_tag_relation.article_tag_relation_id
     *
     * @return the value of dts_article_tag_relation.article_tag_relation_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public String getArticleTagRelationId() {
        return articleTagRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_tag_relation.article_tag_relation_id
     *
     * @param articleTagRelationId the value for dts_article_tag_relation.article_tag_relation_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public void setArticleTagRelationId(String articleTagRelationId) {
        this.articleTagRelationId = articleTagRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_tag_relation.article_id
     *
     * @return the value of dts_article_tag_relation.article_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_tag_relation.article_id
     *
     * @param articleId the value for dts_article_tag_relation.article_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_tag_relation.article_tag_id
     *
     * @return the value of dts_article_tag_relation.article_tag_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public String getArticleTagId() {
        return articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_tag_relation.article_tag_id
     *
     * @param articleTagId the value for dts_article_tag_relation.article_tag_id
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public void setArticleTagId(String articleTagId) {
        this.articleTagId = articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_tag_relation.create_date
     *
     * @return the value of dts_article_tag_relation.create_date
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_tag_relation.create_date
     *
     * @param createDate the value for dts_article_tag_relation.create_date
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_tag_relation
     *
     * @mbg.generated Sun Dec 26 20:04:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleTagRelationId=").append(articleTagRelationId);
        sb.append(", articleId=").append(articleId);
        sb.append(", articleTagId=").append(articleTagId);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}