package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;

public class DtsArticleContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_content.article_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_content.text
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_article_content.markdown
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String markdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_content.article_id
     *
     * @return the value of dts_article_content.article_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_content.article_id
     *
     * @param articleId the value for dts_article_content.article_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_content.text
     *
     * @return the value of dts_article_content.text
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_content.text
     *
     * @param text the value for dts_article_content.text
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_article_content.markdown
     *
     * @return the value of dts_article_content.markdown
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getMarkdown() {
        return markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_article_content.markdown
     *
     * @param markdown the value for dts_article_content.markdown
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setMarkdown(String markdown) {
        this.markdown = markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_article_content
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", text=").append(text);
        sb.append(", markdown=").append(markdown);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}