package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsBlogTagAuthorRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_tag_author_relation.blog_tag_author_relation_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    private String blogTagAuthorRelationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_tag_author_relation.author_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_tag_author_relation.blog_tag_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    private String blogTagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_tag_author_relation.create_date
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_blog_tag_author_relation
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_tag_author_relation.blog_tag_author_relation_id
     *
     * @return the value of dts_blog_tag_author_relation.blog_tag_author_relation_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public String getBlogTagAuthorRelationId() {
        return blogTagAuthorRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_tag_author_relation.blog_tag_author_relation_id
     *
     * @param blogTagAuthorRelationId the value for dts_blog_tag_author_relation.blog_tag_author_relation_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public void setBlogTagAuthorRelationId(String blogTagAuthorRelationId) {
        this.blogTagAuthorRelationId = blogTagAuthorRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_tag_author_relation.author_id
     *
     * @return the value of dts_blog_tag_author_relation.author_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_tag_author_relation.author_id
     *
     * @param authorId the value for dts_blog_tag_author_relation.author_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_tag_author_relation.blog_tag_id
     *
     * @return the value of dts_blog_tag_author_relation.blog_tag_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public String getBlogTagId() {
        return blogTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_tag_author_relation.blog_tag_id
     *
     * @param blogTagId the value for dts_blog_tag_author_relation.blog_tag_id
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public void setBlogTagId(String blogTagId) {
        this.blogTagId = blogTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_tag_author_relation.create_date
     *
     * @return the value of dts_blog_tag_author_relation.create_date
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_tag_author_relation.create_date
     *
     * @param createDate the value for dts_blog_tag_author_relation.create_date
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_author_relation
     *
     * @mbg.generated Sat Dec 25 13:36:32 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", blogTagAuthorRelationId=").append(blogTagAuthorRelationId);
        sb.append(", authorId=").append(authorId);
        sb.append(", blogTagId=").append(blogTagId);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}