package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsBlogComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.blog_comment_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private String blogCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.blog_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.status
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.author_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.content
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_blog_comment.create_date
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.blog_comment_id
     *
     * @return the value of dts_blog_comment.blog_comment_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public String getBlogCommentId() {
        return blogCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.blog_comment_id
     *
     * @param blogCommentId the value for dts_blog_comment.blog_comment_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setBlogCommentId(String blogCommentId) {
        this.blogCommentId = blogCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.blog_id
     *
     * @return the value of dts_blog_comment.blog_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.blog_id
     *
     * @param blogId the value for dts_blog_comment.blog_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.status
     *
     * @return the value of dts_blog_comment.status
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.status
     *
     * @param status the value for dts_blog_comment.status
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.author_id
     *
     * @return the value of dts_blog_comment.author_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.author_id
     *
     * @param authorId the value for dts_blog_comment.author_id
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.content
     *
     * @return the value of dts_blog_comment.content
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.content
     *
     * @param content the value for dts_blog_comment.content
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_blog_comment.create_date
     *
     * @return the value of dts_blog_comment.create_date
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_blog_comment.create_date
     *
     * @param createDate the value for dts_blog_comment.create_date
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", blogCommentId=").append(blogCommentId);
        sb.append(", blogId=").append(blogId);
        sb.append(", status=").append(status);
        sb.append(", authorId=").append(authorId);
        sb.append(", content=").append(content);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}