package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.comment_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private String commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.data_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private String dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.status
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.author_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.content
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_comment.create_date
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_comment
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.comment_id
     *
     * @return the value of dts_comment.comment_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.comment_id
     *
     * @param commentId the value for dts_comment.comment_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.data_id
     *
     * @return the value of dts_comment.data_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.data_id
     *
     * @param dataId the value for dts_comment.data_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.status
     *
     * @return the value of dts_comment.status
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.status
     *
     * @param status the value for dts_comment.status
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.author_id
     *
     * @return the value of dts_comment.author_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.author_id
     *
     * @param authorId the value for dts_comment.author_id
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.content
     *
     * @return the value of dts_comment.content
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.content
     *
     * @param content the value for dts_comment.content
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_comment.create_date
     *
     * @return the value of dts_comment.create_date
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_comment.create_date
     *
     * @param createDate the value for dts_comment.create_date
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", dataId=").append(dataId);
        sb.append(", status=").append(status);
        sb.append(", authorId=").append(authorId);
        sb.append(", content=").append(content);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}