package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsLaoke implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_laoke.laoke_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String laokeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_laoke.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_laoke.text
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_laoke.type
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_laoke.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_laoke.laoke_id
     *
     * @return the value of dts_laoke.laoke_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getLaokeId() {
        return laokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_laoke.laoke_id
     *
     * @param laokeId the value for dts_laoke.laoke_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setLaokeId(String laokeId) {
        this.laokeId = laokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_laoke.author_id
     *
     * @return the value of dts_laoke.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_laoke.author_id
     *
     * @param authorId the value for dts_laoke.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_laoke.text
     *
     * @return the value of dts_laoke.text
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_laoke.text
     *
     * @param text the value for dts_laoke.text
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_laoke.type
     *
     * @return the value of dts_laoke.type
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_laoke.type
     *
     * @param type the value for dts_laoke.type
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_laoke.create_date
     *
     * @return the value of dts_laoke.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_laoke.create_date
     *
     * @param createDate the value for dts_laoke.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", laokeId=").append(laokeId);
        sb.append(", authorId=").append(authorId);
        sb.append(", text=").append(text);
        sb.append(", type=").append(type);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}