package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsLikeBlog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_like_blog.like_blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String likeBlogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_like_blog.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_like_blog.blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_like_blog.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_like_blog
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_like_blog.like_blog_id
     *
     * @return the value of dts_like_blog.like_blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getLikeBlogId() {
        return likeBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_like_blog.like_blog_id
     *
     * @param likeBlogId the value for dts_like_blog.like_blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setLikeBlogId(String likeBlogId) {
        this.likeBlogId = likeBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_like_blog.author_id
     *
     * @return the value of dts_like_blog.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_like_blog.author_id
     *
     * @param authorId the value for dts_like_blog.author_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_like_blog.blog_id
     *
     * @return the value of dts_like_blog.blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_like_blog.blog_id
     *
     * @param blogId the value for dts_like_blog.blog_id
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_like_blog.create_date
     *
     * @return the value of dts_like_blog.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_like_blog.create_date
     *
     * @param createDate the value for dts_like_blog.create_date
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_like_blog
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", likeBlogId=").append(likeBlogId);
        sb.append(", authorId=").append(authorId);
        sb.append(", blogId=").append(blogId);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}