package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;
import java.util.Date;

public class DtsNotice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_notice.notice_id
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private String noticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_notice.title
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_notice.url
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_notice.create_date
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_notice.description
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_notice
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_notice.notice_id
     *
     * @return the value of dts_notice.notice_id
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public String getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_notice.notice_id
     *
     * @param noticeId the value for dts_notice.notice_id
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public void setNoticeId(String noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_notice.title
     *
     * @return the value of dts_notice.title
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_notice.title
     *
     * @param title the value for dts_notice.title
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_notice.url
     *
     * @return the value of dts_notice.url
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_notice.url
     *
     * @param url the value for dts_notice.url
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_notice.create_date
     *
     * @return the value of dts_notice.create_date
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_notice.create_date
     *
     * @param createDate the value for dts_notice.create_date
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dts_notice.description
     *
     * @return the value of dts_notice.description
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dts_notice.description
     *
     * @param description the value for dts_notice.description
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_notice
     *
     * @mbg.generated Sat Nov 20 17:32:51 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noticeId=").append(noticeId);
        sb.append(", title=").append(title);
        sb.append(", url=").append(url);
        sb.append(", createDate=").append(createDate);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}