package net.ttcxy.tang.portal.entity.model;

import java.io.Serializable;

public class UtsAuthor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.author_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.username
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.nickname
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.password
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.mail
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uts_author.signature
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.author_id
     *
     * @return the value of uts_author.author_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.author_id
     *
     * @param authorId the value for uts_author.author_id
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.username
     *
     * @return the value of uts_author.username
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.username
     *
     * @param username the value for uts_author.username
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.nickname
     *
     * @return the value of uts_author.nickname
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.nickname
     *
     * @param nickname the value for uts_author.nickname
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.password
     *
     * @return the value of uts_author.password
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.password
     *
     * @param password the value for uts_author.password
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.mail
     *
     * @return the value of uts_author.mail
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.mail
     *
     * @param mail the value for uts_author.mail
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uts_author.signature
     *
     * @return the value of uts_author.signature
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uts_author.signature
     *
     * @param signature the value for uts_author.signature
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_author
     *
     * @mbg.generated Sun Jan 02 18:18:55 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authorId=").append(authorId);
        sb.append(", username=").append(username);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", mail=").append(mail);
        sb.append(", signature=").append(signature);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}