package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsAdvertise;
import net.ttcxy.tang.portal.entity.model.DtsAdvertiseExample;
import org.apache.ibatis.annotations.Param;

public interface DtsAdvertiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    long countByExample(DtsAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByExample(DtsAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByPrimaryKey(String advertiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insert(DtsAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insertSelective(DtsAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    DtsAdvertise selectByPrimaryKey(String advertiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsAdvertise record, @Param("example") DtsAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExample(@Param("record") DtsAdvertise record, @Param("example") DtsAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKeySelective(DtsAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_advertise
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKey(DtsAdvertise record);
}