package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsBlogComment;
import net.ttcxy.tang.portal.entity.model.DtsBlogCommentExample;
import org.apache.ibatis.annotations.Param;

public interface DtsBlogCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    long countByExample(DtsBlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByExample(DtsBlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByPrimaryKey(String blogCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insert(DtsBlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insertSelective(DtsBlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    DtsBlogComment selectByPrimaryKey(String blogCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsBlogComment record, @Param("example") DtsBlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExample(@Param("record") DtsBlogComment record, @Param("example") DtsBlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKeySelective(DtsBlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_comment
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKey(DtsBlogComment record);
}