package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsBlogSubjectRelation;
import net.ttcxy.tang.portal.entity.model.DtsBlogSubjectRelationExample;
import org.apache.ibatis.annotations.Param;

public interface DtsBlogSubjectRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    long countByExample(DtsBlogSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByExample(DtsBlogSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByPrimaryKey(String blogSubjectRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insert(DtsBlogSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insertSelective(DtsBlogSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    DtsBlogSubjectRelation selectByPrimaryKey(String blogSubjectRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsBlogSubjectRelation record, @Param("example") DtsBlogSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExample(@Param("record") DtsBlogSubjectRelation record, @Param("example") DtsBlogSubjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKeySelective(DtsBlogSubjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_subject_relation
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKey(DtsBlogSubjectRelation record);
}