package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsBlogTagRelation;
import net.ttcxy.tang.portal.entity.model.DtsBlogTagRelationExample;
import org.apache.ibatis.annotations.Param;

public interface DtsBlogTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    long countByExample(DtsBlogTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int deleteByExample(DtsBlogTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int deleteByPrimaryKey(String blogTagRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int insert(DtsBlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int insertSelective(DtsBlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    DtsBlogTagRelation selectByPrimaryKey(String blogTagRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsBlogTagRelation record, @Param("example") DtsBlogTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int updateByExample(@Param("record") DtsBlogTagRelation record, @Param("example") DtsBlogTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int updateByPrimaryKeySelective(DtsBlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_blog_tag_relation
     *
     * @mbg.generated Fri Aug 20 19:50:04 CST 2021
     */
    int updateByPrimaryKey(DtsBlogTagRelation record);
}