package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsComment;
import net.ttcxy.tang.portal.entity.model.DtsCommentExample;
import org.apache.ibatis.annotations.Param;

public interface DtsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    long countByExample(DtsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int deleteByExample(DtsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int insert(DtsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int insertSelective(DtsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    DtsComment selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsComment record, @Param("example") DtsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByExample(@Param("record") DtsComment record, @Param("example") DtsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByPrimaryKeySelective(DtsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_comment
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByPrimaryKey(DtsComment record);
}