package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.DtsLaoke;
import net.ttcxy.tang.portal.entity.model.DtsLaokeExample;
import org.apache.ibatis.annotations.Param;

public interface DtsLaokeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    long countByExample(DtsLaokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int deleteByExample(DtsLaokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int insert(DtsLaoke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int insertSelective(DtsLaoke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") DtsLaoke record, @Param("example") DtsLaokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_laoke
     *
     * @mbg.generated Sun Oct 10 17:08:13 CST 2021
     */
    int updateByExample(@Param("record") DtsLaoke record, @Param("example") DtsLaokeExample example);
}