package net.ttcxy.tang.portal.dao.mapper;

import net.ttcxy.tang.portal.entity.model.UtsFans;
import net.ttcxy.tang.portal.entity.model.UtsFansExample;
import org.apache.ibatis.annotations.Param;

public interface UtsFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    long countByExample(UtsFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByExample(UtsFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int deleteByPrimaryKey(String fansId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insert(UtsFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int insertSelective(UtsFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    UtsFans selectByPrimaryKey(String fansId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") UtsFans record, @Param("example") UtsFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByExample(@Param("record") UtsFans record, @Param("example") UtsFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKeySelective(UtsFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uts_fans
     *
     * @mbg.generated Sun Jul 25 15:28:14 CST 2021
     */
    int updateByPrimaryKey(UtsFans record);
}